### ISSUE TITLE
Number of channel subscribers bug

### ISSUE THREAD

**Issue by superAIyah** [ktnk-dev/py-tg-channel-fetcher#1]
In this line https://github.com/ktnk-dev/teleview/blob/main/teleview/runtime.py#L9 there is a bug, because if you have big channel with many subs. For example https://t.me/s/redakciya_channel telegram shows **1.01M**, and when you do `.replace('.','')` you get 101M and getting subscribers number about 101 million instead of 1.01 milliion. So you should remove `.replace('.','')` at the end of this line.
![image](https://github.com/ktnk-dev/teleview/assets/90476839/ab6e536a-7d56-44b9-866b-7caa1fc2af87)

**Comment by ktnk-dev** [comment]
Thanks for issue! `.replace('.','')` has been removed, bug fixed. Please update to 1.2.2

```py
channel = await teleview.getChannel('redakciya_channel')
print(channel.subscribers) # -> 1010000 (1.01 million)
print(teleview.version) # -> 1.2.2
```
